#!/bin/awk -f
BEGIN { 
  print "<?xml version=\"1.0\"?>";
  print "<?xml-stylesheet type=\"text/xsl\" href=\"xsl/bundles.xsl\"?>";
  print "<bundles>";
  print "  <generated by=\"generate_vim_bundles_xml.sh\" date=\"" strftime("%Y-%m-%d %H:%M:%S") "\"/>";
  print
}
{
  if ( $1 == "[submodule" ) {
    printf "  <bundle ";
  } else if( $1 == "path" ) {
     str = $3;
     sub(/.*\//, "", str);
     printf "name=\"" str "\" ";
  } else if( $1 == "url" ) {
     print "url=\"" $3 "\"/>" ;
  }
}
END { 
  print "</bundles>"; 
}

